name: app
description: A fast, minimalistic backend framework for Dart.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  sarus: ^0.0.1-alpha.14

dev_dependencies:
  build_runner: ^2.5.0
  lints: ^6.0.0
  sarus_gen: ^0.0.1-alpha.1
  sarus_lint: ^0.0.1-alpha.1
